

VALIDATE_ERROR = -1
SUCCESS = 0
DATA_EXISTS = 2
DATA_NOT_FOUND = 3
PAGE_OUT_OF_RANGE = 4
UNAUTHORIZED_ERROR = 5
TOKEN_EXPIRED = 6
ACCESS_EXPIRED = 7
REQ_READY = 'ready'
REQ_QUEUING = 'queuing'
REQ_RUNNING = 'running'
REQ_STOPPED = 'stopped'
REQ_WARNING = 'warning'
REQ_ERROR = 'error'
REQ_DONE = 'done'